title: Theme Handbook
email: support@simpleupdates.com
description: > # this means to ignore newlines until the next property
  This website contains documentation on SimpleUpdates theme APIs and best practices.
twitter_username: SimpleUpdates
github_username:  SimpleUpdates

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: jekyll-theme-primer
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/SimpleUpdates/ThemeHandbook"
